version: '3.5'
services:
  bd:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7777:5432"
  web:
    build:
      context: ./
      args:
        JAR_FILE: build/libs/GraduationProject-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
networks:
  default:
    external:
      name: tests-app-net